project:
  type: website
  output-dir: .

website:
  title: "Ryan Clark"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: Research.html
        text: Research
      - href: Teaching.html
        text: Teaching
      - href: Data.html
        text: Data
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    linkcolor: "#D00000"       # Sets all links to Scarlet

editor: visual

